name: apteka_uz
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.18.0-293.0.dev <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  email_validator: '^2.1.16'
  flutter_svg: ^1.1.1+1
  lottie: ^1.3.0
  fluttertoast: ^8.0.9
  flutter_screenutil: ^5.5.3+2
  json_serializable: ^6.3.1
  modal_bottom_sheet: ^2.0.1
  file_picker: ^3.0.4
  image_picker: ^0.8.5+3
  carousel_slider: ^4.1.1
  dio: ^4.0.6
  flutter_bloc: ^8.1.1
  get_storage: ^2.0.3
  mask_text_input_formatter: ^2.4.0


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0
  build_runner: ^2.2.0


flutter:


  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/lottie/
    - assets/images/
    - assets/svg/




  fonts:
    - family: SFUIDisplay
      fonts:
        - asset: assets/fonts/SFProDisplay-Light.ttf
          weight: 300
        - asset: assets/fonts/SFProDisplay-Regular.ttf
          weight: 400
        - asset: assets/fonts/SFProDisplay-Medium.ttf
          weight: 500
        - asset: assets/fonts/SFProDisplay-Semibold.ttf
          weight: 600
        - asset: assets/fonts/SFProDisplay-Bold.ttf
          weight: 700
        - asset: assets/fonts/SFProDisplay-Black.ttf
          weight: 900
